name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.7.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  rxdart: ^0.27.7
  share_plus: ^8.0.2
  path_provider: ^2.1.2
  http: ^1.2.1