name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.9.1
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  http: ^1.2.2