name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.0.0-dev.2
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.2
  dio: ^4.0.0
  rxdart: ^0.26.0
  share: ^2.0.1
  path_provider: ^2.0.1
