name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 2.0.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  dio: ^4.0.0-beta4
  rxdart: ^0.26.0
  share: ^2.0.0
  path_provider: ^2.0.1
